name: tcm
channels:
  - defaults
dependencies:
  - python=3.7.7 # python dependencies
  - pip=20.3.3
  - notebook=6.2.0
  - rtree=0.9.4 # geospatial dependencies
  - shapely=1.7.1
  - fiona=1.8.13.post1
  - rasterio=1.1.0
  - pyproj=2.6.1.post1
  - gdal=3.0.2
  - numpy=1.19.2 # other dependencies
  - scipy=1.5.2
  - matplotlib=3.3.4
  - scikit-learn=0.23.2
  - scikit-image=0.17.2
  - pip:
    - utm==0.7.0
    - pigeon-jupyter==0.1.0